import { SKILL_BRANCHES, SKILL_NODES, getProgression, canUnlockSkill } from './progression.js';
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const byId = new Map(SKILL_NODES.map(node => [node.id, node]));
const icons = { combat: '⌖', protection: '◇', field: '↟', logistics: '▤' };

export function createProgressionUI(container, actions) {
  container.innerHTML = `<header class="feature-heading"><div><span class="eyebrow"><span class="orange-dash"></span> DEAD FREQUENCY / OPERATOR</span><h2>Operator</h2><p>Vier Spezialisierungen · dauerhafte Vorteile</p></div><div class="progression-overview"><div><span class="micro dim">OPERATOR-LEVEL</span><strong id="skill-level">01</strong></div><div><span class="micro orange">FREIE SKILLPUNKTE</span><strong id="skill-points">3</strong></div></div></header>
    <div class="skill-xp"><div><span id="skill-xp-label">0 XP</span><span id="skill-xp-next">250 XP BIS ZUM NÄCHSTEN PUNKT</span></div><div class="skill-xp-track" role="progressbar" aria-label="Erfahrung bis zum nächsten Level" aria-valuemin="0" aria-valuemax="250"><i id="skill-xp-fill"></i></div></div>
    <p id="skill-lock-note" class="loadout-lock-note" hidden>Deine Skills wurden beim Koop-Beitritt festgelegt. Verlasse die Lobby, um weitere zu lernen.</p>
    <div class="skill-branch-tabs" role="tablist" aria-label="Skill-Spezialisierung">${SKILL_BRANCHES.map((branch,index) => `<button id="skill-tab-${branch.id}" data-skill-branch="${branch.id}" role="tab" aria-controls="skill-branch-${branch.id}" aria-selected="${index===0}" tabindex="${index===0?0:-1}" style="--branch-color:${branch.color}"><span class="branch-icon">${icons[branch.id]}</span><span>${escapeHTML(branch.name.toUpperCase())}<small>${escapeHTML(branch.description)}</small></span><b data-branch-count="${branch.id}">0 / 6</b></button>`).join('')}</div>
    <div class="skill-workspace"><div class="skill-tree-scroll" tabindex="0" aria-label="Skilltree, bei Bedarf scrollen">${SKILL_BRANCHES.map((branch,index) => { const nodes=SKILL_NODES.filter(node=>node.branch===branch.id); return `<section id="skill-branch-${branch.id}" class="skill-branch" role="tabpanel" aria-labelledby="skill-tab-${branch.id}" style="--branch-color:${branch.color}" ${index?'hidden':''}><div class="skill-tree-canvas"><svg class="skill-connections" viewBox="0 0 600 256" preserveAspectRatio="none" aria-hidden="true">${nodes.flatMap(node=>node.requires.map(id=>{const parent=byId.get(id),x1=parent.column*200+100,y1=parent.row*64+51,x2=node.column*200+100,y2=node.row*64+6;return `<path data-skill-edge="${id}:${node.id}" d="M ${x1} ${y1} V ${(y1+y2)/2} H ${x2} V ${y2}"/>`;})).join('')}</svg>${nodes.map(node=>`<button class="skill-node" data-skill-node="${node.id}" style="grid-column:${node.column+1};grid-row:${node.row+1}" aria-pressed="false"><span class="skill-node-meta"><span>${node.row===3?'MEISTERSCHAFT':`STUFE ${node.row+1}`}</span><b>${node.cost} SP</b></span><strong>${escapeHTML(node.name)}</strong><span class="skill-node-status">GESPERRT</span></button>`).join('')}</div></section>`; }).join('')}</div>
    <aside class="skill-detail" aria-labelledby="skill-detail-title"><div class="skill-detail-top"><span id="skill-detail-branch" class="micro">KAMPF</span><span id="skill-detail-status" class="skill-detail-status">VERFÜGBAR</span></div><span id="skill-detail-icon" class="skill-detail-icon" aria-hidden="true">⌖</span><h3 id="skill-detail-title"></h3><p id="skill-detail-description"></p><div class="skill-requirements"><span class="micro dim">VORAUSSETZUNGEN</span><ul id="skill-detail-requires"></ul></div><div class="skill-detail-cost"><span>KOSTEN</span><strong id="skill-detail-cost">1 SKILLPUNKT</strong></div><button id="unlock-skill" class="primary-button" data-action="unlock-skill"><span id="unlock-skill-label">SKILL LERNEN</span><span>↗</span></button><p id="skill-detail-hint" class="skill-detail-hint">Gelernte Skills bleiben auch nach dem Tod erhalten.</p></aside></div>
    <div class="skill-legend"><span><i class="learned"></i> GELERNT</span><span><i class="available"></i> VERFÜGBAR</span><span><i></i> GESPERRT</span><p>3 Startpunkte · je 250 XP ein weiterer Punkt · Skills bleiben bei Tod erhalten</p></div>`;
  let profile = {}, branchId = SKILL_BRANCHES[0].id, selectedId = SKILL_NODES.find(node=>node.branch===branchId&&!node.requires.length).id, locked = false, signature = '';
  const nodeButtons = [...container.querySelectorAll('[data-skill-node]')], branchButtons = [...container.querySelectorAll('[data-skill-branch]')];
  const setText = (id,value) => { const node=container.querySelector(`#${id}`); if(node.textContent!==String(value))node.textContent=value; };
  function renderDetail() {
    const node=byId.get(selectedId),branch=SKILL_BRANCHES.find(branch=>branch.id===node.branch),progress=getProgression(profile),learned=progress.unlocked.includes(node.id),eligible=canUnlockSkill(profile,node.id),requirements=node.requires.every(id=>progress.unlocked.includes(id));
    container.querySelector('.skill-detail').style.setProperty('--branch-color',branch.color);
    setText('skill-detail-branch',branch.name.toUpperCase()); setText('skill-detail-icon',icons[branch.id]);setText('skill-detail-title',node.name);setText('skill-detail-description',node.description);
    setText('skill-detail-status',learned?'GELERNT':locked?'IM KOOP FESTGELEGT':eligible?'VERFÜGBAR':requirements?'PUNKTE FEHLEN':'GESPERRT');
    container.querySelector('#skill-detail-status').dataset.status=learned?'learned':eligible&&!locked?'available':'locked';
    container.querySelector('#skill-detail-requires').innerHTML=node.requires.length?node.requires.map(id=>`<li class="${progress.unlocked.includes(id)?'fulfilled':''}"><span>${progress.unlocked.includes(id)?'✓':'◇'}</span>${escapeHTML(byId.get(id).name)}</li>`).join(''):'<li class="fulfilled"><span>✓</span> Keine vorherigen Skills nötig</li>';
    setText('skill-detail-cost',`${node.cost} ${node.cost===1?'SKILLPUNKT':'SKILLPUNKTE'}`);
    const button=container.querySelector('#unlock-skill');button.disabled=locked||!eligible;button.dataset.skillId=node.id;
    setText('unlock-skill-label',learned?'BEREITS GELERNT':locked?'IM KOOP FESTGELEGT':!requirements?'VORAUSSETZUNG FEHLT':!eligible?'ZU WENIG PUNKTE':'SKILL LERNEN');
    setText('skill-detail-hint',learned?'Aktiv. Dieser Vorteil bleibt dauerhaft erhalten.':locked?'Verlasse die Lobby, um deinen Skilltree zu erweitern.':!requirements?'Lerne zuerst die verbundenen Skills oberhalb dieses Knotens.':'Gelernte Skills bleiben auch nach dem Tod erhalten.');
    for(const button of nodeButtons){const selected=button.dataset.skillNode===selectedId;button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',String(selected));}
  }
  function selectBranch(id) {
    branchId=id;
    for(const button of branchButtons){const active=button.dataset.skillBranch===id;button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;container.querySelector(`#skill-branch-${button.dataset.skillBranch}`).hidden=!active;}
    if(byId.get(selectedId).branch!==id)selectedId=SKILL_NODES.find(node=>node.branch===id&&!node.requires.length).id;
    renderDetail();
  }
  let pending=false;
  async function onClick(event){const branch=event.target.closest('[data-skill-branch]'),node=event.target.closest('[data-skill-node]');if(branch)selectBranch(branch.dataset.skillBranch);else if(node){selectedId=node.dataset.skillNode;renderDetail();}else if(event.target.closest('#unlock-skill')&&!locked&&!pending&&canUnlockSkill(profile,selectedId)){pending=true;container.querySelector('#unlock-skill').disabled=true;try{await actions.unlockSkill?.(selectedId);}finally{pending=false;signature='';}}}
  function onKey(event){const tab=event.target.closest('[data-skill-branch]');if(!tab||!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const index=branchButtons.indexOf(tab),next=event.key==='Home'?0:event.key==='End'?branchButtons.length-1:(index+(event.key==='ArrowRight'?1:-1)+branchButtons.length)%branchButtons.length;selectBranch(branchButtons[next].dataset.skillBranch);branchButtons[next].focus();}
  container.addEventListener('click',onClick);container.addEventListener('keydown',onKey);
  return {update(nextProfile,context={}){profile=nextProfile;locked=!!context.locked;const progress=getProgression(profile),next=JSON.stringify([progress,locked]);if(next===signature)return;signature=next;
    setText('skill-level',String(progress.level).padStart(2,'0'));setText('skill-points',progress.availablePoints);setText('skill-xp-label',`${progress.xp.toLocaleString('de-DE')} XP GESAMT`);setText('skill-xp-next',`${progress.xpToNext} XP BIS ZUM NÄCHSTEN PUNKT`);
    container.querySelector('#skill-xp-fill').style.width=`${progress.xpIntoLevel/(progress.xpIntoLevel+progress.xpToNext)*100}%`;container.querySelector('.skill-xp-track').setAttribute('aria-valuenow',progress.xpIntoLevel);container.querySelector('#skill-lock-note').hidden=!locked;
    for(const button of nodeButtons){const id=button.dataset.skillNode,learned=progress.unlocked.includes(id),available=canUnlockSkill(profile,id);button.dataset.status=learned?'learned':available?'available':'locked';button.querySelector('.skill-node-status').textContent=learned?'✓ GELERNT':available?'VERFÜGBAR':'GESPERRT';}
    for(const edge of container.querySelectorAll('[data-skill-edge]')){const [from,to]=edge.dataset.skillEdge.split(':');edge.classList.toggle('learned',progress.unlocked.includes(to));edge.classList.toggle('reachable',progress.unlocked.includes(from));}
    for(const branch of SKILL_BRANCHES)container.querySelector(`[data-branch-count="${branch.id}"]`).textContent=`${SKILL_NODES.filter(node=>node.branch===branch.id&&progress.unlocked.includes(node.id)).length} / 6`;
    renderDetail();
  },dispose(){container.removeEventListener('click',onClick);container.removeEventListener('keydown',onKey);}};
}
