export const WEAPONS = [
  { id: 'VX-9', name: 'VX-9', category: 'Maschinenpistole', description: 'Leichte Automatik für schnelle Gefechte auf kurze Distanz.', damage: 28, magSize: 24, reserve: 72, fireInterval: .095, reloadSeconds: 1.7, pellets: 1, spread: 0, range: 80, automatic: true, cost: 0, recoilPitch: .005, recoilYaw: .0005, model: 'smg', sound: 'smg' },
  { id: 'AR-4', name: 'AR-4', category: 'Sturmgewehr', description: 'Vielseitiges Sturmgewehr mit kräftigem Einzeltreffer.', damage: 37, magSize: 30, reserve: 120, fireInterval: .12, reloadSeconds: 2.1, pellets: 1, spread: 0, range: 110, automatic: true, cost: 0, recoilPitch: .0066, recoilYaw: .00055, model: 'assault', sound: 'rifle' },
  { id: 'BR-12', name: 'BR-12', category: 'Bullpup-Gewehr', description: 'Kompaktes Gewehr mit hoher Feuerrate und großem Magazin.', damage: 32, magSize: 32, reserve: 96, fireInterval: .082, reloadSeconds: 2.35, pellets: 1, spread: .003, range: 100, automatic: true, cost: 250, recoilPitch: .016, recoilYaw: .00055, model: 'bullpup', sound: 'bullpup' },
  { id: 'SG-8', name: 'SG-8', category: 'Pump-Schrotflinte', description: 'Zehn Schrotkugeln pro Patrone; nach jedem Schuss repetieren.', damage: 12, magSize: 8, reserve: 32, fireInterval: .82, reloadSeconds: 3.2, pellets: 10, spread: .065, range: 34, automatic: false, cost: 175, recoilPitch: .027, recoilYaw: .00065, model: 'shotgun', sound: 'shotgun' },
  { id: 'DMR-7', name: 'DMR-7', category: 'Präzisionsgewehr', description: 'Halbautomatische Präzision: ein kräftiger Schuss pro Abzug.', damage: 62, magSize: 12, reserve: 48, fireInterval: .34, reloadSeconds: 2.55, pellets: 1, spread: 0, range: 170, automatic: false, cost: 325, recoilPitch: .022, recoilYaw: .0004, model: 'marksman', sound: 'marksman' },
  { id: 'SR-90', name: 'SR-90', category: 'Repetier-Scharfschützengewehr', description: 'Hohe Reichweite und Durchschlagskraft mit bewusster Repetierpause.', damage: 112, magSize: 5, reserve: 20, fireInterval: 1.2, reloadSeconds: 3.1, pellets: 1, spread: 0, range: 240, automatic: false, cost: 550, recoilPitch: .036, recoilYaw: .00035, model: 'sniper', sound: 'sniper' },
  { id: 'MG-60', name: 'MG-60', category: 'Leichtes Maschinengewehr', description: 'Langes Unterdrückungsfeuer; der Gurtwechsel braucht Zeit.', damage: 26, magSize: 60, reserve: 180, fireInterval: .095, reloadSeconds: 4.4, pellets: 1, spread: .006, range: 130, automatic: true, cost: 425, recoilPitch: .019, recoilYaw: .0006, model: 'machinegun', sound: 'machinegun' },
  { id: 'RV-6', name: 'RV-6', category: 'Revolver', description: 'Sechs kräftige Schüsse in einem günstigen, kompakten Paket.', damage: 55, magSize: 6, reserve: 36, fireInterval: .43, reloadSeconds: 2.65, pellets: 1, spread: 0, range: 75, automatic: false, cost: 0, recoilPitch: .024, recoilYaw: .0006, model: 'revolver', sound: 'revolver' },
];
const byId = new Map(WEAPONS.map(weapon => [weapon.id, weapon]));
export const getWeapon = id => byId.get(id) ?? null;
export const defaultWeapon = kit => kit === 'assault' ? 'AR-4' : 'VX-9';
